services:
  db-master:
    image: mysql:8.0
    container_name: db-master
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_tareas_db
    ports:
      - "3310:3306"
    volumes:
      - ./database/init-master:/docker-entrypoint-initdb.d
      - master-data:/var/lib/mysql
    command: >
      --server-id=1
      --log-bin=mysql-bin
      --binlog-do-db=app_tareas_db
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 10

  db-slave:
    image: mysql:8.0
    container_name: db-slave
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3311:3306"
    volumes:
      - slave-data:/var/lib/mysql
    command: >
      --server-id=2
      --relay-log=relay-log-bin
      --read-only=1
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
    depends_on:
      db-master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 10

  replication-setup:
    image: mysql:8.0
    container_name: replication_setup
    depends_on:
      db-master:
        condition: service_healthy
      db-slave:
        condition: service_healthy
    volumes:
      - ./database/scripts/setup-replication.sh:/setup-replication.sh
    entrypoint: ["bash", "-c", "sed 's/\\r$//' /setup-replication.sh > /tmp/setup.sh && bash /tmp/setup.sh"]
    restart: "no"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ad
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: db-master,db-slave
    ports:
      - "8080:80"
    depends_on:
      - db-master
      - db-slave

  backend-node1:
    build: ./backend
    container_name: app_backend_1
    environment:
      DB_HOST: db-master
      DB_PORT: 3306
      PORT: 3000
      NODE_ID: "nodo-1"
    depends_on:
      db-master:
        condition: service_healthy

  backend-node2:
    build: ./backend
    container_name: app_backend_2
    environment:
      DB_HOST: db-master
      DB_PORT: 3306
      PORT: 3000
      NODE_ID: "nodo-2"
    depends_on:
      db-master:
        condition: service_healthy

  backend-node3:
    build: ./backend
    container_name: app_backend_3
    environment:
      DB_HOST: db-master
      DB_PORT: 3306
      PORT: 3000
      NODE_ID: "nodo-3"
    depends_on:
      db-master:
        condition: service_healthy

  lb:
    build: ./nginx
    container_name: nginx_lb
    ports:
      - "3000:80"
    depends_on:
      - backend-node1
      - backend-node2
      - backend-node3

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:3000/api
    container_name: app_frontend
    ports:
      - "80:80"
    depends_on:
      - lb

volumes:
  master-data:
  slave-data:
